[package]
name = "eratosthenes-pistion"
version = "0.1.1"
authors = ["David Caiazzo <dc@comfortablynull.com>"]

[dependencies]
rand = "0.3"
piston = "0.1.3"
piston2d-graphics = "0.0.48"
piston2d-opengl_graphics = "0.0.17"
pistoncore-glutin_window = "0.0.9"
